import { z } from 'zod';
import { access, writeFile, stat } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { execProcess } from '../../lib/exec.js';

const CONSUMER_LAUNCHER_FILES = {
  windows: {
    start: 'consumer-start.bat',
    stop: 'consumer-stop.bat',
  },
  linux: {
    start: 'consumer-start.sh',
    stop: 'consumer-stop.sh',
  },
} as const;

// Files written by 'restforge-consumer-deploy' into its output folder
// (cli/consumer-deploy.js:651-658). Used for the pre-flight existence check that
// keeps the CLI away from its interactive overwrite prompt.
const DEPLOY_FILES = ['ecosystem.config.js', 'consumer-manager.sh'] as const;

// Default control-API port of 'restforge-consumer' when --port is omitted
// (cli/consumer.js parseArgs default). The stop script needs a concrete port.
const DEFAULT_CONTROL_PORT = 3001;

const DEFAULT_DEPLOY_DIR = 'deploy';

const TEMPLATE_WINDOWS_HOST_START = `@echo off
REM RESTForge Kafka Consumer Launcher
REM Generated by restforge-mcp
REM Project:  {{PROJECT}}
REM Config:   {{CONFIG}}
REM Consumer: {{CONSUMER_LABEL}}
REM Port:     {{PORT}}

echo Starting RESTForge Kafka Consumer...
echo Project:  {{PROJECT}}
echo Config:   {{CONFIG}}
echo Consumer: {{CONSUMER_LABEL}}
echo Port:     {{PORT}}
echo.
echo Kafka must be reachable before this starts; the consumer exits if it is not.
echo To stop: press Ctrl+C in this window, or run consumer-stop.bat in another terminal.
echo.

npx restforge-consumer --project={{PROJECT}} --config={{CONFIG}}{{EXTRA_ARGS}}
`;

const TEMPLATE_WINDOWS_HOST_STOP = `@echo off
REM RESTForge Kafka Consumer Stopper
REM Generated by restforge-mcp

set PORT={{PORT}}
echo Stopping RESTForge Kafka Consumer on control port %PORT%...

set FOUND=0
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :%PORT% ^| findstr LISTENING') do (
    echo Killing PID %%a
    taskkill /F /PID %%a /T
    set FOUND=1
    goto :done
)

:done
if "%FOUND%"=="0" (
    echo No process found listening on port %PORT%.
    exit /b 1
)
`;

const TEMPLATE_LINUX_HOST_START = `#!/bin/bash
# RESTForge Kafka Consumer Launcher
# Generated by restforge-mcp
# Project:  {{PROJECT}}
# Config:   {{CONFIG}}
# Consumer: {{CONSUMER_LABEL}}
# Port:     {{PORT}}

echo "Starting RESTForge Kafka Consumer..."
echo "Project:  {{PROJECT}}"
echo "Config:   {{CONFIG}}"
echo "Consumer: {{CONSUMER_LABEL}}"
echo "Port:     {{PORT}}"
echo ""
echo "Kafka must be reachable before this starts; the consumer exits if it is not."
echo "To stop: press Ctrl+C, or run ./consumer-stop.sh in another terminal."
echo ""

exec npx restforge-consumer --project={{PROJECT}} --config={{CONFIG}}{{EXTRA_ARGS}}
`;

const TEMPLATE_LINUX_HOST_STOP = `#!/bin/bash
# RESTForge Kafka Consumer Stopper
# Generated by restforge-mcp

PORT={{PORT}}
echo "Stopping RESTForge Kafka Consumer on control port $PORT..."

PID=""
if command -v lsof >/dev/null 2>&1; then
    PID=$(lsof -ti:$PORT 2>/dev/null | head -1)
fi
if [ -z "$PID" ] && command -v fuser >/dev/null 2>&1; then
    PID=$(fuser \${PORT}/tcp 2>/dev/null | awk '{print $1}')
fi

if [ -z "$PID" ]; then
    echo "No process found listening on port $PORT."
    exit 1
fi

echo "Killing PID $PID..."
kill -TERM "$PID" 2>/dev/null
sleep 1
if kill -0 "$PID" 2>/dev/null; then
    kill -KILL "$PID" 2>/dev/null
fi
echo "Done."
`;

interface ExtraArgsOptions {
  consumer?: string;
  port?: number;
}

/**
 * Build the optional part of the 'restforge-consumer' command line.
 * Only the '--flag=value' form is emitted: cli/consumer.js parses with
 * startsWith('--flag='), so a space-separated form would be silently ignored.
 */
function buildExtraArgs(opts: ExtraArgsOptions): string {
  const parts: string[] = [];
  if (opts.consumer) {
    parts.push(`--consumer=${opts.consumer}`);
  }
  if (opts.port !== undefined) {
    parts.push(`--port=${opts.port}`);
  }
  return parts.length > 0 ? ' ' + parts.join(' ') : '';
}

function applyTemplate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? '');
}

export function registerRuntimeGenerateConsumerLauncher(server: McpServer): void {
  server.registerTool(
    'runtime_generate_consumer_launcher',
    {
      title: 'Generate RESTForge Kafka Consumer Launcher',
      description: `Prepare a way to run the Kafka consumer runtime ('restforge-consumer') of a project. This tool does NOT run the consumer — it only writes files that the user executes themselves. Same two-step pattern as 'runtime_generate_launcher': this server prepares, the user runs. A consumer spawned from an AI session would die with the session; a script or PM2 process owned by the user's terminal survives it.

MODES:
- mode=host: writes a start/stop pair in the project root (file names are FIXED):
  * windows: consumer-start.bat, consumer-stop.bat
  * linux:   consumer-start.sh, consumer-stop.sh
  The start script runs 'npx restforge-consumer --project=<p> --config=<c> [--consumer=<name>] [--port=<n>]'
  in the foreground ('exec' on Linux). The stop script kills whatever listens on the
  consumer control-API port (netstat/taskkill on Windows, lsof/fuser + kill on Linux) —
  no PID file needed.
- mode=pm2: does NOT hand-write an ecosystem file. It runs
  'npx restforge-consumer-deploy' in the project folder, which is the command whose only
  job is to WRITE deploy files (it never starts a consumer). It produces, in the output
  folder (default ./deploy/): ecosystem.config.js (one PM2 app per consumer, ports
  auto-incremented from the base port) and consumer-manager.sh (interactive PM2 helper).
  It also creates ./logs/pm2/ in the project folder. 'os' is ignored in this mode — the
  files produced are the same on every platform.

REQUIRED FLAGS AND ARGUMENT FORM:
- 'config' is REQUIRED for both modes. 'restforge-consumer' refuses to start without it
  ("Error: --config=<FILE.env> is required", exit 1), and so does 'restforge-consumer-deploy'.
  The value must end with .env or the consumer rejects it.
- Both binaries parse only the '--flag=value' form; the space-separated form is silently
  ignored. The generated script therefore always uses '='.
- '--license' / '--license-server' are deliberately NOT exposed: the license is read from
  the environment/config, same choice as 'runtime_generate_launcher'.

USE WHEN:
- The user asks to run/start a Kafka consumer, e.g. "jalankan consumer", "run the kafka consumer", "deploy consumer ke pm2"
- Right after a consumer was generated with 'codegen_create_kafka_consumer' and the user asks how to run it
- The user wants a production PM2 deployment for the consumers of a project

DO NOT USE FOR:
- Starting/stopping the consumer itself -> the user runs the generated script or 'pm2 start' themselves
- The REST API server -> use 'runtime_generate_launcher' (different binary, different files)
- Creating the consumer source code -> use 'codegen_create_kafka_consumer'

Preconditions:
- The cwd must exist.
- 'config' must end with .env.
- mode=pm2 additionally requires @restforgejs/platform installed in the project
  (node_modules), because the binary enforces a local install.
- Without 'overwrite': in host mode existing launcher files are skipped, and in pm2 mode
  the tool refuses to run the CLI at all when deploy files already exist (the CLI would
  otherwise stop at an interactive overwrite prompt that this server cannot answer).
  'overwrite' maps to '--force' in pm2 mode only.

PRESENTATION GUIDANCE:
- Match the user's language.
- Never mention internal tool names. Refer to the produced files by their visible names
  (e.g. 'consumer-start.bat', 'deploy/ecosystem.config.js').
- Say plainly that this assistant does NOT start the consumer — the user runs it, so it
  keeps running after this session ends.
- Remind the user that a Kafka broker must be reachable; the consumer exits otherwise.
- For pm2 mode: PM2 must be installed globally first (npm install -g pm2). Do not auto-install.
- Do not paste the JSON envelope unless explicitly asked; summarise location, files, how to
  start and how to stop.`,
      inputSchema: {
        cwd: z
          .string()
          .min(1)
          .describe('Absolute path of the project folder root (output goes here)'),
        os: z
          .enum(['windows', 'linux'])
          .describe(
            'Target OS for mode=host: windows produces .bat, linux produces .sh. Ignored for mode=pm2.'
          ),
        mode: z
          .enum(['host', 'pm2'])
          .describe(
            'host writes a start/stop script pair that runs npx restforge-consumer; pm2 delegates to npx restforge-consumer-deploy which writes the PM2 deploy files'
          ),
        project: z
          .string()
          .min(1)
          .describe(
            'Project name (filename in src/modules/ without .js). Passed as --project=<name>. REQUIRED.'
          ),
        config: z
          .string()
          .min(1)
          .describe(
            'Config file name in config/ folder, must end with .env (e.g. db-connection.env). Passed as --config=<filename>. REQUIRED — the consumer binaries refuse to run without it.'
          ),
        consumer: z
          .string()
          .optional()
          .describe(
            'Specific consumer name. Omit to run/deploy every consumer registered in the project.'
          ),
        port: z
          .number()
          .int()
          .min(1)
          .max(65535)
          .optional()
          .describe(
            `Control-API port. Omit to use the binary default (${DEFAULT_CONTROL_PORT}). In pm2 mode this is the base port; further consumers get port+1, port+2, ...`
          ),
        output: z
          .string()
          .optional()
          .describe(
            'mode=pm2 only: output folder for the deploy files, relative to cwd (default ./deploy/). Ignored in host mode.'
          ),
        overwrite: z
          .boolean()
          .default(false)
          .describe(
            'If true, overwrite existing files (host mode: rewrite the scripts; pm2 mode: pass --force to the CLI). If false, existing files are left untouched.'
          ),
      },
      annotations: {
        title: 'Generate Consumer Launcher',
        // Writes launcher/deploy files, may overwrite them, and the pm2 branch shells out
        // to a file-generating CLI — mirrors runtime_generate_launcher.
        readOnlyHint: false,
        idempotentHint: false,
        destructiveHint: true,
      },
    },
    async (input) => {
      const { cwd, os, mode, project, config, consumer, port, output, overwrite } = input;

      if (!config.endsWith('.env')) {
        return {
          content: [
            {
              type: 'text',
              text: `Precondition not met: the config file name must end with .env (received: ${config}).

For the assistant:
- The consumer binary rejects any other extension before it does anything else.
- Ask the user for the correct config file name (e.g. db-connection.env), or look it up first.
- Match the user's language. Do not mention internal tool names.`,
            },
          ],
          isError: false,
        };
      }

      const projectCwd = resolve(cwd);
      try {
        await access(projectCwd);
      } catch {
        return {
          content: [
            {
              type: 'text',
              text: `Precondition not met: cwd does not exist: ${projectCwd}

For the assistant:
- The target folder is missing. Suggest creating it first or verifying the path.
- Match the user's language. Do not mention internal tool names.`,
            },
          ],
          isError: false,
        };
      }

      const effectivePort = port ?? DEFAULT_CONTROL_PORT;

      if (mode === 'pm2') {
        try {
          await access(join(projectCwd, 'node_modules', '@restforgejs', 'platform'));
        } catch {
          return {
            content: [
              {
                type: 'text',
                text: `Precondition not met: the RESTForge package is not installed in this project.

Project path: ${projectCwd}
Expected location: node_modules/@restforgejs/platform
Requested project: ${project}

For the assistant:
- The deploy generator only runs from a local install of the package.
- Suggest installing the package in this project first, then retry. Do not mention internal tool names.`,
              },
            ],
            isError: false,
          };
        }

        const outputDir = resolve(projectCwd, output ?? DEFAULT_DEPLOY_DIR);
        const existingDeployFiles: string[] = [];
        for (const f of DEPLOY_FILES) {
          const fullPath = join(outputDir, f);
          try {
            await stat(fullPath);
            existingDeployFiles.push(fullPath);
          } catch {
            // absent
          }
        }

        if (existingDeployFiles.length > 0 && !overwrite) {
          return {
            content: [
              {
                type: 'text',
                text: `Nothing generated: deploy files already exist and overwrite=false.

Project path: ${projectCwd}
Output folder: ${outputDir}
Existing files:
${existingDeployFiles.map((f) => `- ${f}`).join('\n')}

For the assistant:
- Nothing was written and no command was run. The deploy generator would stop at an interactive overwrite prompt, which this server cannot answer, so it was not started at all.
- Ask the user whether to overwrite the existing deploy files (call again with overwrite=true) or write to a different output folder.
- Match the user's language. Do not mention internal tool names.`,
              },
            ],
            isError: false,
          };
        }

        const args = [
          'restforge-consumer-deploy',
          `--project=${project}`,
          `--config=${config}`,
        ];
        if (consumer) args.push(`--consumer=${consumer}`);
        if (port !== undefined) args.push(`--port=${port}`);
        if (output) args.push(`--output=${output}`);
        if (overwrite) args.push('--force');

        // stdin: 'ignore' as a second guard — if the CLI ever reaches its readline
        // prompt anyway, EOF ends it instead of hanging until the timeout.
        const result = await execProcess('npx', args, {
          cwd: projectCwd,
          timeout: 60_000,
          stdin: 'ignore',
        });

        if (!result.success) {
          return {
            content: [
              {
                type: 'text',
                text: `Failed to generate the consumer deploy files.

Project path: ${projectCwd}
Project: ${project}
Config: ${config}
Consumer: ${consumer ?? '(all consumers)'}
Output folder: ${outputDir}
Command: ${result.command}
Exit code: ${result.exitCode}

--- CLI output ---
stdout:
${result.stdout}

stderr:
${result.stderr}
--- end CLI output ---

For the assistant:
- Nothing was deployed and the consumer was NOT started (this command only writes files).
- Summarise the most likely cause from the CLI output in plain language (common causes: the named consumer does not exist under src/consumers/<project>/, the project has no consumer at all, or the config file name is wrong).
- Offer to retry once the cause is resolved. Do not mention internal tool names.`,
              },
            ],
            isError: true,
          };
        }

        const writtenDeployFiles: { path: string; size_bytes: number }[] = [];
        for (const f of DEPLOY_FILES) {
          const fullPath = join(outputDir, f);
          try {
            const st = await stat(fullPath);
            writtenDeployFiles.push({ path: fullPath, size_bytes: st.size });
          } catch {
            // not produced for this invocation
          }
        }

        const pm2Envelope = {
          cwd: projectCwd,
          mode,
          project,
          config,
          consumer: consumer ?? null,
          port: port ?? null,
          base_port_effective: effectivePort,
          output_dir: outputDir,
          delegated_command: result.command,
          exit_code: result.exitCode,
          generated_files: writtenDeployFiles,
          also_created: join(projectCwd, 'logs', 'pm2'),
          consumer_started: false,
        };

        return {
          content: [
            {
              type: 'text',
              text: `Consumer deploy files generated (PM2 mode). The consumer itself was NOT started.

Project path: ${projectCwd}
Project: ${project}
Config: ${config}
Consumer: ${consumer ?? '(all consumers)'}
Base port: ${effectivePort}
Output folder: ${outputDir}
Command: ${result.command}
Generated: ${writtenDeployFiles.length}

--- Generation Result (JSON) ---
${JSON.stringify(pm2Envelope, null, 2)}
--- end Generation Result (JSON) ---

--- CLI output ---
${result.stdout}
--- end CLI output ---

For the assistant:
- Tell the user the PM2 deploy files are in ${outputDir}: ecosystem.config.js and consumer-manager.sh. A logs/pm2 folder was created in the project root for the PM2 log files.
- To start: the user runs 'pm2 start ecosystem.config.js' from that folder (or './consumer-manager.sh' for the interactive helper). To stop: 'pm2 stop ecosystem.config.js'.
- Warn that PM2 must be installed globally first (npm install -g pm2); this server does not install it.
- Remind the user a reachable Kafka broker is required, otherwise the PM2 processes will keep restarting.
- The consumer must be started by the user — a process spawned from this session would die with the session.
- Match the user's language. Do not mention internal tool names.`,
            },
          ],
          isError: false,
        };
      }

      // mode === 'host'
      const extra = buildExtraArgs({ consumer, port });

      const vars: Record<string, string> = {
        PROJECT: project,
        CONFIG: config,
        CONSUMER_LABEL: consumer ?? '(all consumers)',
        PORT: String(effectivePort),
        EXTRA_ARGS: extra,
      };

      const startFile = CONSUMER_LAUNCHER_FILES[os].start;
      const stopFile = CONSUMER_LAUNCHER_FILES[os].stop;

      type FileSpec = { fileName: string; content: string };
      const filesToWrite: FileSpec[] =
        os === 'windows'
          ? [
              { fileName: startFile, content: applyTemplate(TEMPLATE_WINDOWS_HOST_START, vars) },
              { fileName: stopFile, content: applyTemplate(TEMPLATE_WINDOWS_HOST_STOP, vars) },
            ]
          : [
              { fileName: startFile, content: applyTemplate(TEMPLATE_LINUX_HOST_START, vars) },
              { fileName: stopFile, content: applyTemplate(TEMPLATE_LINUX_HOST_STOP, vars) },
            ];

      const generated: { path: string; size_bytes: number; overwritten: boolean }[] = [];
      const skipped: { path: string; reason: string }[] = [];

      for (const f of filesToWrite) {
        const fullPath = join(projectCwd, f.fileName);
        let existed = false;
        try {
          await stat(fullPath);
          existed = true;
        } catch {
          existed = false;
        }

        if (existed && !overwrite) {
          skipped.push({ path: fullPath, reason: 'already exists, overwrite=false' });
          continue;
        }
        try {
          await writeFile(fullPath, f.content, 'utf8');
          generated.push({
            path: fullPath,
            size_bytes: Buffer.byteLength(f.content, 'utf8'),
            overwritten: existed,
          });
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          return {
            content: [{ type: 'text', text: `Failed to write ${fullPath}: ${msg}` }],
            isError: true,
          };
        }
      }

      const runCommand = `npx restforge-consumer --project=${project} --config=${config}${extra}`;

      const envelope = {
        cwd: projectCwd,
        os,
        mode,
        project,
        config,
        consumer: consumer ?? null,
        port: port ?? null,
        control_port_effective: effectivePort,
        run_command: runCommand,
        generated_files: generated,
        skipped_files: skipped,
        stop_method: `kill the process listening on control port ${effectivePort} (invoked by ${stopFile})`,
        consumer_started: false,
      };

      const summary =
        generated.length === filesToWrite.length
          ? `Generated ${generated.length} consumer launcher file${generated.length === 1 ? '' : 's'}.`
          : `Generated ${generated.length}; skipped ${skipped.length} (already exist, overwrite=false).`;

      const startCommand = os === 'windows' ? `.\\${startFile}` : `./${startFile}`;
      const stopCommand = os === 'windows' ? stopFile : `./${stopFile}`;

      return {
        content: [
          {
            type: 'text',
            text: `${summary} The consumer itself was NOT started.

Project path: ${projectCwd}
OS: ${os}
Mode: ${mode}
Project: ${project}
Config: ${config}
Consumer: ${consumer ?? '(all consumers)'}
Control port: ${effectivePort}${port === undefined ? ' (binary default, not passed as a flag)' : ''}
Generated: ${generated.length}
Skipped: ${skipped.length}

--- Generation Result (JSON) ---
${JSON.stringify(envelope, null, 2)}
--- end Generation Result (JSON) ---

For the assistant:
- ${
              generated.length > 0
                ? `Tell the user the consumer launcher was written to the project root. To start: ${startCommand}. To stop: ${stopCommand}.`
                : `Nothing was generated because the files already exist and overwrite=false. Ask the user whether to overwrite (call again with overwrite=true).`
            }
- The generated command is: ${runCommand}
- Remind the user a reachable Kafka broker is required before starting; the consumer exits otherwise.
- The consumer runs in the user's terminal — the process belongs to the user's session, NOT to this AI session. Do not start it from here.
- The stop script kills whatever listens on control port ${effectivePort}; if the user changes the port, regenerate the pair.
- Match the user's language. Do not mention internal tool names.`,
          },
        ],
        isError: false,
      };
    }
  );
}
